name: DreamCauldron
main: com.MrSweeter.DreamCauldron.DreamCauldron
version: 1.1
author: MrSweeter / SweetDream
description: Magic Cauldron, change your loot

commands:
    dcreload:
        description: Reload config !
        usage: /dcreload

permissions: 
    dreamCauldron.reload:
        description: Allow you to reload config of DreamCauldron
        default: op